#!/bin/bash
id=`docker ps -q`
if [[ $id ]]; then
	RUN=`echo "Stopping nginx server" >> /var/log/setup/setup.log`
	STOP=`docker stop $id`
	echo "Removing nginx container" >> /var/log/setup/setup.log
	docker rm -v $(docker ps -a -q -f status=exited)
fi

rm -rf /mnt/nginx/run
rm -rf /mnt/nginx/docker/Dockerfile
rm -rf /mnt/nginx/build
rm -rf /mnt/nginx/src
rm -rf /mnt/nginx/dist